# Jekyll
livereload: true

# Site
repository: ardabeyazoglu/modern-resume-theme
# favicon: images/favicon.ico

# Personal info
name: Arda Beyazoğlu
title: Software Engineer
#email: arda[at]beyazoglu.com
website: ardabeyazoglu.com
blog: blog.ardabeyazoglu.com
location: Ljubljana / Slovenia

# Social links
twitter_username: ardabeyazoglu
github_username: ardabeyazoglu
gitlab_username: ardabeyazoglu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ardabeyazoglu
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# codementor_username: ardabeyazoglu
stackoverflow_username: 2756657
medium_username: ardabeyazoglu

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a full-stack software engineer in Ljubljana. 
  I started coding in 2003, using old school visual basic and php4 for web. Since then, I've experienced various techs by working in different types of software, from desktop to mostly web apps and taking care of different roles. My favourite stack includes <mark>php</mark>, <mark>mysql</mark> <mark>javascript</mark> on <mark>ubuntu</mark>; however, I also like coding in different languages, and learning recent stacks to stay up-to-date.
  <br><br>
  I always try to do my work with engineering principles, plan in advance, split into parts, prioritize, decouple and test. Although there is no limit of learning and the entire stack nowadays is too deep and wide for a single person, I would like to know as many things as possible, and enjoy learning. This is why I read a lot about recent trends and techs, such as devops, containers, serverless, machine learning. One can use any knowledge at any point in his life.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Jobs

# Education Section
# educaton_title: Education

# Skills Section
skills_title: Experience
skills_others: |
  php javascript nodejs c# 
  mysql percona redis memcached firebase dynamodb sphinxsearch manticore mongodb gearman 
  winforms python auto-ml 
  linux ubuntu redhat supervisor ldap tcp/ip 
  socket.io websocket electronjs reactjs vuejs extjs framework7
  zendframework phalconphp oauth2 restapi soap
  vsto cordova docker

# More Section
more_title:
more_content: | # this will include new lines to allow paragraphs
  Coming soon...

# Footer
footer_show_references: false

# Build settings
# remote_theme: ardabeyazoglu/modern-resume-theme

google_analytics: UA-5077009-2

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
