# Jekyll
livereload: true

# Site
repository: ardabeyazoglu/modern-resume-theme
# favicon: images/favicon.ico

# Personal info
name: Arda Beyazoğlu
title: Software Engineer
#email: arda[at]beyazoglu.com
website: ardabeyazoglu.com
blog: blog.ardabeyazoglu.com
location: Ljubljana / Slovenia

# Social links
twitter_username: ardabeyazoglu
github_username: ardabeyazoglu
# gitlab_username: ardabeyazoglu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ardabeyazoglu
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# codementor_username: ardabeyazoglu
stackoverflow_username: 2756657
medium_username: ardabeyazoglu

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a software engineer in Ljubljana. 
  I started coding in 2003 using no longer available tools, then switched to php-mysql stack and I've been working in web applications since then. Because I worked on medium-to-large client facing projects in a small team, I took care of different roles throughout my career. Mostly working as core developer and team lead, I have experienced a long list of challenges, problems and their solutions, from system design and devops practices, to structuring databases and core backend development. One can use any knowledge at any point in his life, so I keep learning to improve my skills and stay up-to-date.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
# educaton_title: Education

# Skills Section
skills_title: Experience
skills_others: |
  php javascript nodejs c# python
  mysql pxc redis memcached firebase dynamodb sphinxsearch mongodb gearman 
  linux ubuntu redhat supervisor ldap tcpdump
  socket.io websocket electronjs reactjs vuejs extjs framework7
  zendframework phalconphp oauth soap
  vsto cordova docker vagrant gitlab-ci

# More Section
more_title:
more_content: | # this will include new lines to allow paragraphs
  Coming soon...

# Footer
footer_show_references: false

# Build settings
# remote_theme: ardabeyazoglu/modern-resume-theme

google_analytics: UA-5077009-2

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
