# Jekyll
livereload: true

# Site
repository: ardabeyazoglu/modern-resume-theme
# favicon: images/favicon.ico

# Personal info
name: Arda Beyazoğlu
title: Senior Software Engineer
email: arda[at]beyazoglu.com
website: ardabeyazoglu.com
location: Ljubljana / Slovenia

# Social links
#twitter_username: arda_beyazoglu
github_username: ardabeyazoglu
gitlab_username: ardabeyazoglu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ardabeyazoglu
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# codementor_username: ardabeyazoglu
stackoverflow_username: 2756657

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a full-stack software developer who loves coding. I've been developing software since 2005, and I am experienced mostly in **web development** using <mark>php</mark>, <mark>mysql</mark> and <mark>javascript</mark>. Sometimes I code in **c#** and **python** for different stuff, but I enjoy web development more in general.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Skills Section
skills_title: Skills
skills_others: |
  redis memcached firebase dynamodb sphinxsearch mongodb gearman
  nodejs C# python auto-ml
  socket.io websocket electronjs
  php-zendframework php-phalcon php-swoole
  fb-graph-api ms-graph-api ms-office-addins

# More Section
more_title:
more_content: | # this will include new lines to allow paragraphs
  Coming soon...

# Footer
footer_show_references: false

# Build settings
# remote_theme: ardabeyazoglu/modern-resume-theme

google_analytics: UA-5077009-2

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
